# -*- coding: utf-8 -*-
"""worldTribe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4MxY0RmYzszyGtXvrk8g-vQw1EElO-S
"""

!pip install flask-cors pyngrok beautifulsoup4

import requests
import json
from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok

app = Flask(__name__)
CORS(app)

# GANTI DENGAN API KEY SERPER ANDA
SERPER_API_KEY = "insert_your_serper_API_key"
ngrok.set_auth_token("insert_your_serper_token")

def get_verified_info(suku_name):
    """Mengambil deskripsi yang panjang, tuntas, dan mendalam"""
    url = "https://google.serper.dev/search"
    headers = {
        'X-API-KEY': SERPER_API_KEY,
        'Content-Type': 'application/json'
    }

    # Query lebih spesifik untuk mendapatkan data sejarah tuntas
    payload = json.dumps({"q": f"sejarah lengkap kebudayaan suku {suku_name}"})

    try:
        response = requests.post(url, headers=headers, data=payload, timeout=10)
        res = response.json()

        full_description = ""

        # 1. Ambil Knowledge Graph (Data resmi Google yang biasanya tuntas)
        if 'knowledgeGraph' in res:
            full_description = res['knowledgeGraph'].get('description', '')

        # 2. Gabungkan dengan hasil organik agar lebih panjang
        organic_results = res.get('organic', [])
        # Mengambil 3 snippet pertama untuk digabungkan menjadi uraian lengkap
        snippets = [item.get('snippet', '') for item in organic_results[:3]]
        combined_snippets = " ".join(snippets)

        if full_description:
            full_text = f"{full_description} {combined_snippets}"
        else:
            full_text = combined_snippets

        # 3. Pembersihan: Menghapus titik-titik gantung agar tidak terkesan hoax
        final_text = full_text.replace("...", "").strip()

        # Pastikan kalimat terakhir benar-benar tuntas (berhenti di titik terakhir)
        if "." in final_text:
            last_dot = final_text.rfind(".")
            final_text = final_text[:last_dot + 1]

        return final_text if len(final_text) > 10 else "Informasi tidak tersedia."

    except:
        return "Gagal mengambil uraian lengkap."

def get_images(suku_name):
    """Mencari foto pakaian adat dan rumah adat"""
    url = "https://google.serper.dev/images"
    headers = {'X-API-KEY': SERPER_API_KEY, 'Content-Type': 'application/json'}

    # Cari Pakaian Adat
    q_baju = f"pakaian adat suku {suku_name} asli"
    res_baju = requests.post(url, headers=headers, json={"q": q_baju}).json()
    foto_baju = res_baju.get('images', [{}])[0].get('imageUrl', 'not_found')

    # Cari Rumah Adat
    q_rumah = f"rumah adat suku {suku_name} asli"
    res_rumah = requests.post(url, headers=headers, json={"q": q_rumah}).json()
    foto_rumah = res_rumah.get('images', [{}])[0].get('imageUrl', 'not_found')

    return foto_baju, foto_rumah

@app.route('/translate', methods=['POST'])
def translate():
    data = request.get_json()
    query = data.get('query', '')

    deskripsi = get_verified_info(query)
    foto_baju, foto_rumah = get_images(query)

    return jsonify({
        "deskripsi": deskripsi,
        "foto_bajuAdat": foto_baju,
        "foto_rumahAdat": foto_rumah
    })

# Menjalankan Ngrok
public_url = ngrok.connect(5000)
print(f"URL API ANDA: {public_url.public_url}/translate")
app.run(port=5000)